Fix undefined reference to can_*()
Problem reported by Martin Guy.

Saying:
$ ./go picoc
[...]
src/modules/can.c:183: error: 'can_setup' undeclared here (not in a function)
src/modules/can.c:184: error: 'can_send' undeclared here (not in a function)
src/modules/can.c:185: error: 'can_recv' undeclared here (not in a function)

The functions were renamed to
picoc_can_*() earlier. Fixed.