lua_lcd.c: #include modcommon.h within Lua section causes issues
In file included from src/platform/stm32/lua_lcd.c:21:0:
src/modules/modcommon.h:11:3: error: expected specifier-qualifier-list before 'u32'
scons: *** [src/platform/stm32/lua_lcd.o] Error 1
scons: building terminated because of errors.

Comment the line for now. Lua now seems to be compiling for
the stm32f103re.